language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- python -c "import datetime; print(datetime.datetime.utcnow().strftime('3.%Y%m%d.%H%M%S'))" > $TRAVIS_BUILD_DIR/VERSION
- ls -al $TRAVIS_BUILD_DIR
- echo "$TRAVIS_BUILD_DIR/VERSION"
- cat $TRAVIS_BUILD_DIR/VERSION
deploy:
  provider: pypi
  user: ManiacalLabs
  password:
    secure: gtzpSBgf+Tr8hz7MdSFnVzEu0NqsmSlSCpNJMPp0EqQckLt5MKkR7buHsvKEg2fBmTgohSPAu5wWEmIzNyi+90yR3CPaAGeAEQ4oMPjsW+PPL4hldg/wP+1hc9YeHWTw+r3k0Xo03Jm7/zHgCuIbfX9GoBhk7RGiOktVpuIM9NErt4ZvQ4QQtoH8CxE/aw2z6tzmCfWJbKgM/j9QvJjavOVqVp0wDAar1tWAq3G/Kgz/seWs7kJipHlSsNFdsw2nM6k2Y1quOq423ylvNjNeZnlZR+lsoYBX3jwqjJxDM0avpNpQIIr/ooY6cfoEuo6dGyoWLZxVRs25QYTJJ6I7mGRbjyiv8myRGLFNh3fpNGhSPecyZoeFjKJ0SlfUqJzUdVzkrf/EoY3bnWJp2Z+fgG+4jByivtAkwyHxnl2Y2tTCuxCP2NJSfhsUCHAt1HJCu5C5GH2UGDhopabPZPXyZsLuBIYMv2jfj4exqVZJzdeHqDv4DXNMkhUYE/4AqBS1GA3AFKdKjWFR1ZD95jOWvox0wGYWbOGTGE3ZSNQDtQMxH2Epj7H6wln2koehlU1k49ig6G2mdYivizdxeC2/B2uR/qPRXJpavAg8p7wBqBx7Z7+ai3ykJX1qi4QLO6VFb3uG1WVu095dYA475hpy/rjmVDeOQJlSUwl/S/gyHjM=
  on:
    repo: ManiacalLabs/BiblioPixelAnimations
    branch: master
